# Generated by Django 5.2.4 on 2025-07-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'premio', 'ronda', 'nominado')},
        ),
        migrations.AddField(
            model_name='voto',
            name='orden_ronda2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden en Ronda 2 (1=Oro, 2=Plata, 3=Bronce)'),
        ),
    ]
