# Generated by Django 5.2.4 on 2025-07-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_alter_voto_unique_together_voto_orden_ronda2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premio',
            options={'ordering': ['nombre'], 'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.RemoveField(
            model_name='premio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_resultados_publicados',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación de Resultados'),
        ),
        migrations.AddField(
            model_name='premio',
            name='ganador_bronce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_bronce', to='votaciones.nominado', verbose_name='Ganador Bronce'),
        ),
        migrations.AddField(
            model_name='premio',
            name='ganador_oro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_oro', to='votaciones.nominado', verbose_name='Ganador Oro'),
        ),
        migrations.AddField(
            model_name='premio',
            name='ganador_plata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_plata', to='votaciones.nominado', verbose_name='Ganador Plata'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto para votación'), ('cerrado', 'Votación cerrada'), ('resultados', 'Resultados publicados')], default='abierto', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Premio'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='ronda_actual',
            field=models.PositiveIntegerField(default=1, verbose_name='Ronda Actual de Votación'),
        ),
    ]
