# Generated by Django 5.2.4 on 2025-07-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_alter_usuario_options_remove_usuario_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha sido verificado por un administrador y puede votar.'),
        ),
    ]
