# Generated by Django 5.2.4 on 2025-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0005_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='premio',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
