# Generated by Django 5.2.4 on 2025-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_premio_image_url_premio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Foto de Perfil'),
        ),
    ]
