# Generated by Django 5.2.4 on 2025-09-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0007_usuario_descripcion_usuario_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='tipo',
            field=models.CharField(choices=[('directo', 'Directo (Usuarios)'), ('indirecto', 'Indirecto (Frases/Objetos)')], default='directo', max_length=20, verbose_name='Tipo de Premio'),
        ),
    ]
