# Generated by Django 5.2.4 on 2025-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0008_premio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='vinculos_requeridos',
            field=models.PositiveIntegerField(default=1, verbose_name='Usuarios vinculados requeridos'),
        ),
    ]
