# Generated by Django 5.2.4 on 2025-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0009_premio_vinculos_requeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='participante_tag',
            field=models.CharField(blank=True, choices=[('Jose', 'Jose'), ('Garcia', 'Garcia'), ('Felipe', 'Felipe'), ('Catedra', 'Catedra'), ('Richi', 'Richi'), ('Alex', 'Alex'), ('Chema', 'Chema'), ('Dani', 'Dani'), ('Alejandra', 'Alejandra'), ('Sandra', 'Sandra'), ('Rocio', 'Rocio'), ('Joaquin', 'Joaquin'), ('Silvia', 'Silvia'), ('Gema', 'Gema'), ('Ana', 'Ana'), ('Tomas', 'Tomas')], help_text='Etiqueta del slot de participante asignado (único).', max_length=32, null=True, unique=True),
        ),
    ]
