# Generated by Django 5.2.4 on 2025-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0010_usuario_participante_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='ganadores_historicos',
            field=models.JSONField(blank=True, default=list, help_text="Lista de los últimos ganadores: [{ 'year': 2024, 'name': 'Nombre' }, ...]", null=True),
        ),
    ]
