# Generated by Django 5.2.4 on 2025-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0011_premio_ganadores_historicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_actual', models.CharField(choices=[('preparacion', 'Preparación'), ('votacion_1', 'Votación Ronda 1'), ('votacion_2', 'Votación Ronda 2'), ('finalizado', 'Finalizado')], default='preparacion', max_length=20, verbose_name='Fase Actual del Sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.AlterModelOptions(
            name='sugerencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'ordering': ['-fecha_voto'], 'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_fin_ronda1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Ronda 1'),
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_fin_ronda2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Ronda 2'),
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_inicio_ronda1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Ronda 1'),
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_inicio_ronda2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Ronda 2'),
        ),
        migrations.AddField(
            model_name='voto',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='voto',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'En preparación'), ('votacion_1', 'Votación Ronda 1'), ('votacion_2', 'Votación Ronda 2'), ('finalizado', 'Finalizado')], default='preparacion', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='ronda_actual',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ronda Actual'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='orden_ronda2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica para la Ronda 2', null=True, verbose_name='Orden en Ronda 2 (1=Oro, 2=Plata, 3=Bronce)'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='ronda',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ronda de Votación'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['usuario', 'premio', 'ronda'], name='votaciones__usuario_1f205e_idx'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['premio', 'ronda', 'fecha_voto'], name='votaciones__premio__ed6848_idx'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['fecha_voto'], name='votaciones__fecha_v_c6823a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('usuario', 'premio', 'ronda', 'nominado'), name='unico_voto_por_nominado_ronda'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('orden_ronda2__in', [1, 2, 3]), ('ronda', 2)), models.Q(('ronda', 1), ('orden_ronda2__isnull', True)), _connector='OR'), name='orden_valido_para_ronda2'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(condition=models.Q(('ronda', 2)), fields=('usuario', 'premio', 'ronda', 'orden_ronda2'), name='unico_orden_por_voto_ronda2'),
        ),
    ]
